Repository GazzolaLab/PyElastica, pull requests merged in 2022-07, with the labels that each got.

#117 116 rigid body rod contact
  elastica/joint.py
  examples/README.md
  examples/RigidBodyCases/RodRigidBodyContact/post_processing.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_inclined_contact.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_parallel_contact.py
Labels: bug

#124 121 rigid body rod contact friction
  elastica/joint.py
  examples/RigidBodyCases/RodRigidBodyContact/post_processing.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_friction.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_friction_case.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_friction_phase_space.py
Labels: enhancement

#123 Filter Damper class
  docs/api/damping.rst
  elastica/dissipation.py
  elastica/typing.py
  tests/test_dissipation.py
Labels: enhancement

#120 [WIP] Update timestep values for the new damping module
  examples/AxialStretchingCase/axial_stretching.py
  examples/Binder/2_Slithering_Snake.ipynb
  examples/ContinuumFlagellaCase/continuum_flagella.py
  examples/ContinuumSnakeCase/continuum_snake.py
  examples/ExperimentalCases/ParallelConnectionExample/parallel_connection_example.py
  examples/FrictionValidationCases/rolling_friction_initial_velocity.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/spherical_joint.py
  examples/MuscularFlagella/muscular_flagella.py
  examples/MuscularSnake/muscular_snake.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  examples/TimoshenkoBeamCase/convergence_timoshenko.py
  examples/TimoshenkoBeamCase/timoshenko.py
Labels: enhancement

#130 Update ExportCallback
  elastica/callback_functions.py
  tests/__init__.py
  tests/test_boundary_conditions.py
  tests/test_callback_functions.py
  tests/test_interaction.py
Labels: bug

#138 Remove _elastica_numba folder while keeping _elastica_numba.py
  elastica/_elastica_numba.py
  elastica/_elastica_numba/_boundary_conditions.py
Labels: enhancement

#139 Update CI: Add sphinx build
  .github/workflows/ci-sphinx.yml
  docs/_static/assets/Logo.png
  docs/conf.py
  docs/requirements.txt
  elastica/dissipation.py
Labels: documentation, update

#141 [WIP] Poetry setup for PyElastica (#101)
  .coveragerc
  .github/workflows/ci-sphinx.yml
  .github/workflows/main.yml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/wip_PR.yml
  CONTRIBUTING.md
  Makefile
  docs/README.md
  docs/requirements.txt
  elastica/boundary_conditions.py
  elastica/rod/cosserat_rod.py
  elastica/timestepper/__init__.py
  examples/FlexibleSwingingPendulumCase/flexible_swinging_pendulum.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/optional-requirements.txt
  poetry.lock
  pyproject.toml
  requirements.txt
  setup.py
  tests/requirements.txt
  tests/test_rod_initialisation.py
Labels: enhancement

#146 update: numba disable jit flag in poetry command
  .github/workflows/main.yml
  Makefile
Labels: enhancement

#151 (#150) add pre commit to pyelastica
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  poetry.lock
  pyproject.toml
Labels: enhancement

#156 Update makefile commands: test
  .github/workflows/main.yml
  Makefile
Labels: invalid

#155 (#153) fix poetry install instructions
  CONTRIBUTING.md
  Makefile
Labels: invalid, prio:high

#157 docs: correct endpoint forces docstring
  elastica/external_forces.py
Labels: invalid, prio:high

#143 Address #148 by adding `ConfigurableFixedConstraint` boundary condition class
  docs/api/constraints.rst
  elastica/boundary_conditions.py
  examples/BoundaryConditionsCases/bc_cases_postprocessing.py
  examples/BoundaryConditionsCases/general_constraint_allow_yaw.py
  examples/README.md
  tests/test_boundary_conditions.py
Labels: enhancement, discussion

#160 update: matplotlib and ffmpeg dependencies
  Makefile
  examples/README.md
  poetry.lock
  pyproject.toml
Labels: update, prio:high

#162 update: remove sys append calls in examples
  examples/AxialStretchingCase/axial_stretching.py
  examples/BoundaryConditionsCases/bc_cases_postprocessing.py
  examples/BoundaryConditionsCases/general_constraint_allow_yaw.py
  examples/ButterflyCase/butterfly.py
  examples/ContinuumFlagellaCase/continuum_flagella.py
  examples/ContinuumSnakeCase/continuum_snake.py
  examples/ExperimentalCases/ParallelConnectionExample/parallel_connection_example.py
  examples/FlexibleSwingingPendulumCase/flexible_swinging_pendulum.py
  examples/FrictionValidationCases/axial_friction.py
  examples/FrictionValidationCases/friction_validation_postprocessing.py
  examples/FrictionValidationCases/rolling_friction_initial_velocity.py
  examples/FrictionValidationCases/rolling_friction_on_inclined_plane.py
  examples/FrictionValidationCases/rolling_friction_torque.py
  examples/HelicalBucklingCase/convergence_helicalbuckling.py
  examples/HelicalBucklingCase/helicalbuckling.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/fixed_joint_torsion.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/spherical_joint.py
  examples/MuscularFlagella/muscular_flagella.py
  examples/MuscularSnake/muscular_snake.py
  examples/RestartExample/restart_example.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_friction.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_validation.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_with_y_normal.py
  examples/RigidBodyCases/rigid_cylinder_rotational_motion_case.py
  examples/RigidBodyCases/rigid_cylinder_translational_motion_case.py
  examples/RigidBodyCases/rigid_sphere_rotational_motion_case.py
  examples/RigidBodyCases/rigid_sphere_translational_motion_case.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/TimoshenkoBeamCase/convergence_timoshenko.py
  examples/TimoshenkoBeamCase/timoshenko.py
  examples/Visualization/ContinuumSnakeVisualization/continuum_snake.py
  examples/Visualization/ContinuumSnakeVisualization/continuum_snake_render.py
Labels: update, prio:medium

#163 refac: exp damper --> analytical linear damper
  docs/api/damping.rst
  docs/guide/workflow.md
  elastica/dissipation.py
  elastica/rod/factory_function.py
  examples/AxialStretchingCase/axial_stretching.py
  examples/Binder/1_Timoshenko_Beam.ipynb
  examples/Binder/2_Slithering_Snake.ipynb
  examples/BoundaryConditionsCases/general_constraint_allow_yaw.py
  examples/ContinuumFlagellaCase/continuum_flagella.py
  examples/ContinuumSnakeCase/continuum_snake.py
  examples/ExperimentalCases/ParallelConnectionExample/parallel_connection_example.py
  examples/FrictionValidationCases/rolling_friction_initial_velocity.py
  examples/HelicalBucklingCase/convergence_helicalbuckling.py
  examples/HelicalBucklingCase/helicalbuckling.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/fixed_joint_torsion.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/spherical_joint.py
  examples/MuscularFlagella/muscular_flagella.py
  examples/MuscularSnake/muscular_snake.py
  examples/RestartExample/restart_example.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/TimoshenkoBeamCase/convergence_timoshenko.py
  examples/TimoshenkoBeamCase/timoshenko.py
  tests/test_dissipation.py
  tests/test_rod_initialisation.py
  tests/test_wrappers/test_damping.py
Labels: update, prio:high
