Repository GazzolaLab/PyElastica, pull requests merged in 2022-08, with the labels that each got.

#172 update: Damping values for rod-rigid body contact cases (#171)
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_friction.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_validation.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_with_y_normal.py
Labels: update, prio:high

#170 (#164) fix damping force direction
  elastica/experimental/connection_contact_joint/parallel_connection.py
  elastica/joint.py
  examples/ExperimentalCases/GenericSystemConnectionCases/generic_system_type_fixed_joint.py
  examples/ExperimentalCases/GenericSystemConnectionCases/generic_system_type_spherical_joint.py
  examples/ExperimentalCases/GenericSystemConnectionCases/joint_cases_postprocessing.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/fixed_joint_torsion.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/joint_cases_postprocessing.py
  examples/JointCases/spherical_joint.py
  tests/test_joint.py
Labels: invalid, prio:high

#177 Refactor: `wrappers` -> `modules`
  docs/api/simulator.rst
  docs/guide/workflow.md
  elastica/__init__.py
  elastica/boundary_conditions.py
  elastica/modules/__init__.py
  elastica/modules/base_system.py
  elastica/modules/callbacks.py
  elastica/modules/connections.py
  elastica/modules/constraints.py
  elastica/modules/damping.py
  elastica/modules/forcing.py
  elastica/modules/memory_block.py
  elastica/systems/__init__.py
  elastica/wrappers.py
  examples/Binder/1_Timoshenko_Beam.ipynb
  examples/Binder/2_Slithering_Snake.ipynb
  examples/Visualization/ContinuumSnakeVisualization/continuum_snake.py
  tests/test_modules/test_base_system.py
  tests/test_modules/test_callbacks.py
  tests/test_modules/test_connections.py
  tests/test_modules/test_constraints.py
  tests/test_modules/test_damping.py
  tests/test_modules/test_forcing.py
  tests/test_modules/test_memory_block.py
  tests/test_restart.py
Labels: update, prio:low

#173 Dynamic validation example (#111)
  examples/DynamicCantileverCase/analytical_dynamic_cantilever.py
  examples/DynamicCantileverCase/dynamic_cantilever.py
  examples/DynamicCantileverCase/dynamic_cantilever_phase_space.py
  examples/DynamicCantileverCase/dynamic_cantilever_post_processing.py
  examples/DynamicCantileverCase/dynamic_cantilever_visualization.py
  examples/README.md
Labels: enhancement, prio:low

#191 Refactor: change typings in forcing/constraints/connections to SystemType or RodType
  elastica/boundary_conditions.py
  elastica/dissipation.py
  elastica/external_forces.py
  elastica/joint.py
Labels: documentation, prio:low

#192 (#152) Windows CI fix
  .github/workflows/main.yml
  tests/test_callback_functions.py
Labels: invalid, prio:medium

#175 (#165) feat: autoflake funtionality
  Makefile
  elastica/_calculus.py
  elastica/_linalg.py
  elastica/_rotations.py
  elastica/boundary_conditions.py
  elastica/experimental/connection_contact_joint/generic_system_type_connection.py
  elastica/experimental/interaction.py
  elastica/external_forces.py
  elastica/memory_block/memory_block_rigid_body.py
  elastica/modules/base_system.py
  elastica/modules/constraints.py
  elastica/reset_functions_for_block_structure/_reset_ghost_vector_or_scalar.py
  elastica/rigidbody/data_structures.py
  elastica/rigidbody/rigid_body.py
  elastica/rod/cosserat_rod.py
  elastica/rod/data_structures.py
  elastica/systems/analytical.py
  elastica/timestepper/_stepper_interface.py
  elastica/timestepper/symplectic_steppers.py
  examples/ExperimentalCases/GenericSystemConnectionCases/joint_cases_postprocessing.py
  examples/HelicalBucklingCase/helicalbuckling_postprocessing.py
  examples/JointCases/joint_cases_postprocessing.py
  examples/MuscularFlagella/connection_flagella.py
  examples/MuscularFlagella/post_processing.py
  examples/MuscularSnake/muscle_forces.py
  examples/MuscularSnake/post_processing.py
  examples/RigidBodyCases/RodRigidBodyContact/post_processing.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/RodContactCase/post_processing.py
  examples/Visualization/ContinuumSnakeVisualization/continuum_snake.py
  examples/Visualization/_povmacros.py
  examples/convergence_functions.py
  poetry.lock
  pyproject.toml
  tests/test_boundary_conditions.py
  tests/test_callback_functions.py
  tests/test_data_structures.py
  tests/test_external_forces.py
  tests/test_math/test_governing_equations.py
  tests/test_math/test_rotation_non_numba_impls.py
  tests/test_math/test_timestepper.py
  tests/test_modules/test_callbacks.py
  tests/test_modules/test_connections.py
  tests/test_rigid_body/test_cylinder.py
  tests/test_rigid_body/test_rigid_body_data_structures.py
  tests/test_rigid_body/test_sphere.py
  tests/test_rod/test_cosserat_rod.py
  tests/test_rod/test_knot_theory.py
  tests/test_rod/test_rods.py
  tests/test_timesteppers.py
Labels: enhancement, prio:low
