Repository GazzolaLab/PyElastica, pull requests merged in 2022-05, with the labels that each got.

#82 Adds significant digits to shear coefficient (#79)
  elastica/rod/factory_function.py
  tests/test_rod_initialisation.py
Labels: invalid, update

#84 Blacken example files (#83)
  Makefile
  examples/ExperimentalCases/ParallelConnectionExample/parallel_connection_example.py
  examples/MuscularSnake/muscle_forces.py
  examples/MuscularSnake/muscular_snake.py
  examples/MuscularSnake/post_processing.py
  examples/RestartExample/restart_example.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
Labels: enhancement

#94 hotfix coverage: cannot omit ellipsis
  .coveragerc
Labels: bug

#96 95 missing imports example cases
  examples/AxialStretchingCase/axial_stretching.py
  examples/ButterflyCase/butterfly.py
  examples/ContinuumSnakeCase/continuum_snake.py
  examples/FlexibleSwingingPendulumCase/flexible_swinging_pendulum.py
  examples/MuscularFlagella/muscular_flagella.py
  examples/MuscularSnake/muscular_snake.py
  examples/RestartExample/restart_example.py
  examples/RigidBodyCases/rigid_cylinder_rotational_motion_case.py
  examples/RigidBodyCases/rigid_cylinder_translational_motion_case.py
  examples/RigidBodyCases/rigid_sphere_rotational_motion_case.py
  examples/RigidBodyCases/rigid_sphere_translational_motion_case.py
Labels: bug

#97 Track velocity norms as dynamic proxies in Axial stretching and Timoshenko examples
  .coveragerc
  .github/workflows/main.yml
  examples/AxialStretchingCase/axial_stretching.py
  examples/ButterflyCase/butterfly.py
  examples/ContinuumSnakeCase/continuum_snake.py
  examples/FlexibleSwingingPendulumCase/flexible_swinging_pendulum.py
  examples/MuscularFlagella/muscular_flagella.py
  examples/MuscularSnake/muscular_snake.py
  examples/RestartExample/restart_example.py
  examples/RigidBodyCases/rigid_cylinder_rotational_motion_case.py
  examples/RigidBodyCases/rigid_cylinder_translational_motion_case.py
  examples/RigidBodyCases/rigid_sphere_rotational_motion_case.py
  examples/RigidBodyCases/rigid_sphere_translational_motion_case.py
  examples/TimoshenkoBeamCase/timoshenko.py
Labels: update
