Repository GazzolaLab/PyElastica, pull requests merged in 2022-02, with the labels that each got.

#51 Update cosserat_rod parameter documentation
  elastica/rod/cosserat_rod.py
Labels: documentation

#53 Documentation updates using MyST
  CONTRIBUTING.md
  docs/README.md
  docs/README.rst
  docs/api/documentation.rst
  docs/api/elastica++.rst
  docs/conf.py
  docs/index.rst
  docs/intro_page.rst
  docs/overview/getting_started.md
  docs/overview/installation.rst
  docs/overview/welcome_page.rst
  docs/requirements.txt
  elastica/boundary_conditions.py
  elastica/callback_functions.py
  elastica/external_forces.py
  elastica/joint.py
  elastica/rod/__init__.py
  elastica/rod/cosserat_rod.py
Labels: documentation, enhancement

#56 Update on constraint module; Add generalized constraint class
  elastica/_elastica_numba/_boundary_conditions.py
  elastica/boundary_conditions.py
  elastica/wrappers/constraints.py
  examples/AxialStretchingCase/axial_stretching.py
  examples/FlexibleSwingingPendulumCase/flexible_swinging_pendulum.py
  examples/FrictionValidationCases/axial_friction.py
  examples/FrictionValidationCases/rolling_friction_initial_velocity.py
  examples/FrictionValidationCases/rolling_friction_on_inclined_plane.py
  examples/FrictionValidationCases/rolling_friction_torque.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/spherical_joint.py
  examples/RestartExample/restart_example.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/TimoshenkoBeamCase/convergence_timoshenko.py
  examples/TimoshenkoBeamCase/timoshenko.py
  tests/test_boundary_conditions.py
  tests/test_elastica_numba/test_boundary_conditions_nb.py
  tests/test_wrappers/test_base_system.py
  tests/test_wrappers/test_constraints.py
Labels: enhancement, update

#57 Update unit tests
  .coveragerc
  elastica/_elastica_numba/_boundary_conditions.py
  elastica/boundary_conditions.py
  elastica/wrappers/constraints.py
  examples/AxialStretchingCase/axial_stretching.py
  examples/FlexibleSwingingPendulumCase/flexible_swinging_pendulum.py
  examples/FrictionValidationCases/axial_friction.py
  examples/FrictionValidationCases/rolling_friction_initial_velocity.py
  examples/FrictionValidationCases/rolling_friction_on_inclined_plane.py
  examples/FrictionValidationCases/rolling_friction_torque.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/spherical_joint.py
  examples/RestartExample/restart_example.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/TimoshenkoBeamCase/convergence_timoshenko.py
  examples/TimoshenkoBeamCase/timoshenko.py
  tests/test_boundary_conditions.py
  tests/test_elastica_numba/test_boundary_conditions_nb.py
  tests/test_elastica_numba/test_external_forces_nb.py
  tests/test_elastica_numba/test_interaction_nb.py
  tests/test_elastica_numba/test_rod_nb.py
  tests/test_external_forces.py
  tests/test_interaction.py
  tests/test_math/test_calculus_nb.py
  tests/test_math/test_governing_equations.py
  tests/test_math/test_linalg.py
  tests/test_math/test_memory_block_with_symplectic_timestepper.py
  tests/test_math/test_reset_ghosts.py
  tests/test_math/test_rotation_non_numba_impls.py
  tests/test_math/test_rotations.py
  tests/test_math/test_timestepper.py
  tests/test_rod.py
  tests/test_transformations.py
  tests/test_wrappers/test_base_system.py
  tests/test_wrappers/test_constraints.py
Labels: update

#63 Doc update skim449
  docs/advanced/LocalizedForceTorque.md
  docs/api/analytical.rst
  docs/api/callback.rst
  docs/api/constraints.rst
  docs/api/utility.rst
  docs/conf.py
  docs/guide/discretization.md
  docs/guide/example_cases.rst
  docs/guide/pybind.md
  docs/guide/visualization.md
  docs/guide/workflow.md
  docs/index.rst
  docs/intro_page.rst
  docs/overview/getting_started.md
  docs/overview/installation.md
Labels: documentation
