Repository GazzolaLab/PyElastica, pull requests merged in 2022-01, with the labels that each got.

#40 Update contact model
  RELEASE.md
  elastica/_elastica_numba/_joint.py
  elastica/joint.py
  examples/README.md
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/RodContactCase/post_processing.py
Labels: enhancement, update

#46 Patch - integrate
  elastica/timestepper/__init__.py
Labels: enhancement

#47 Callback mechanism had ambiguous floating-point division (issue 35)
  elastica/timestepper/symplectic_steppers.py
  elastica/wrappers/base_system.py
  elastica/wrappers/callbacks.py
  tests/test_wrappers/test_base_system.py
  tests/test_wrappers/test_callbacks.py
Labels: bug, enhancement

#48 Collected experimental codes into separate modules (issue 42)
  elastica/experimental/__init__.py
  elastica/experimental/interaction.py
  elastica/interaction.py
Labels: update

#50 Update v0.2.1
  RELEASE.md
  elastica/_elastica_numba/_joint.py
  elastica/experimental/__init__.py
  elastica/experimental/interaction.py
  elastica/interaction.py
  elastica/joint.py
  elastica/timestepper/__init__.py
  elastica/timestepper/symplectic_steppers.py
  elastica/wrappers/base_system.py
  elastica/wrappers/callbacks.py
  examples/ButterflyCase/.gitignore
  examples/ButterflyCase/butterfly.py
  examples/README.md
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/RodContactCase/post_processing.py
  requirements.txt
  setup.py
  tests/test_wrappers/test_base_system.py
  tests/test_wrappers/test_callbacks.py
Labels: update
