Repository GazzolaLab/PyElastica, pull requests merged in 2022-06, with the labels that each got.

#87 [WIP] (#81) dissipation constant fix
  elastica/memory_block/memory_block_rod.py
  elastica/rod/cosserat_rod.py
  elastica/rod/factory_function.py
  examples/AxialStretchingCase/axial_stretching.py
  examples/Binder/1_Timoshenko_Beam.ipynb
  examples/Binder/2_Slithering_Snake.ipynb
  examples/ContinuumFlagellaCase/continuum_flagella.py
  examples/ContinuumSnakeCase/continuum_snake.py
  examples/ExperimentalCases/ParallelConnectionExample/parallel_connection_example.py
  examples/HelicalBucklingCase/convergence_helicalbuckling.py
  examples/HelicalBucklingCase/helicalbuckling.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/spherical_joint.py
  examples/MuscularFlagella/muscular_flagella.py
  examples/MuscularSnake/muscular_snake.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/TimoshenkoBeamCase/convergence_timoshenko.py
  examples/TimoshenkoBeamCase/timoshenko.py
  tests/test_math/test_governing_equations.py
  tests/test_math/test_memory_block_with_symplectic_timestepper.py
  tests/test_memory_block_validity.py
  tests/test_rod_initialisation.py
  tests/test_wrappers/test_memory_block.py
Labels: bug, help wanted, update

#98 (#80) node to element interpolation fix
  elastica/interaction.py
  tests/test_interaction.py
Labels: bug, enhancement

#109 108 contact examples and fixes
  examples/RigidBodyCases/RodRigidBodyContact/post_processing.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_validation.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_with_y_normal.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
Labels: bug, enhancement

#110 refactor EndPointForcesSinusoidal example and test cases
  docs/api/external_forces.rst
  elastica/external_forces.py
  examples/JointCases/external_force_class_for_joint_test.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/spherical_joint.py
  tests/test_external_forces.py
Labels: enhancement

#115 (#102) Codeowners setup
  docs/CODEOWNERS
Labels: enhancement

#114 Refactor internal dissipation as external addon damping module
  README.md
  docs/README.md
  docs/api/damping.rst
  docs/api/simulator.rst
  docs/guide/workflow.md
  docs/index.rst
  elastica/__init__.py
  elastica/dissipation.py
  elastica/rod/factory_function.py
  elastica/typing.py
  elastica/wrappers/__init__.py
  elastica/wrappers/damping.py
  examples/AxialStretchingCase/axial_stretching.py
  examples/Binder/1_Timoshenko_Beam.ipynb
  examples/Binder/2_Slithering_Snake.ipynb
  examples/ButterflyCase/butterfly.py
  examples/ContinuumFlagellaCase/continuum_flagella.py
  examples/ContinuumSnakeCase/continuum_snake.py
  examples/ExperimentalCases/ParallelConnectionExample/parallel_connection_example.py
  examples/FlexibleSwingingPendulumCase/flexible_swinging_pendulum.py
  examples/FrictionValidationCases/axial_friction.py
  examples/FrictionValidationCases/rolling_friction_initial_velocity.py
  examples/FrictionValidationCases/rolling_friction_on_inclined_plane.py
  examples/FrictionValidationCases/rolling_friction_torque.py
  examples/HelicalBucklingCase/convergence_helicalbuckling.py
  examples/HelicalBucklingCase/helicalbuckling.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/spherical_joint.py
  examples/MuscularFlagella/muscular_flagella.py
  examples/MuscularSnake/muscular_snake.py
  examples/RestartExample/restart_example.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/TimoshenkoBeamCase/convergence_timoshenko.py
  examples/TimoshenkoBeamCase/timoshenko.py
  tests/test_dissipation.py
  tests/test_rod_initialisation.py
  tests/test_wrappers/test_damping.py
Labels: enhancement, update
