Repository GazzolaLab/PyElastica, pull requests merged in 2023-10, with the labels that each got.

#298 Rod sphere contact
  elastica/contact_forces.py
  elastica/contact_utils.py
  examples/Binder/1_Timoshenko_Beam.ipynb
  examples/Binder/2_Slithering_Snake.ipynb
  tests/test_contact_classes.py
  tests/test_contact_functions.py
  tests/test_contact_utils.py
Labels: enhancement, prio:medium

#294 RodMeshSurfaceContact class init
  elastica/contact_forces.py
  elastica/contact_utils.py
  elastica/mesh/mesh_initializer.py
  elastica/surface/__init__.py
  elastica/surface/mesh_surface.py
  examples/Binder/1_Timoshenko_Beam.ipynb
  examples/Binder/2_Slithering_Snake.ipynb
  tests/test_mesh_init.py
  tests/test_surface/test_mesh_surface.py
Labels: enhancement, prio:high

#301 266 rod and sphere contact temp
  elastica/__init__.py
  elastica/contact_forces.py
  elastica/contact_utils.py
  elastica/modules/contact.py
  examples/Binder/1_Timoshenko_Beam.ipynb
  examples/Binder/2_Slithering_Snake.ipynb
  tests/test_contact_classes.py
  tests/test_contact_functions.py
  tests/test_contact_utils.py
  tests/test_modules/test_contact.py
Labels: enhancement, prio:medium

#307 (#286) python 3.11 support
  .github/workflows/main.yml
  README.md
  poetry.lock
  pyproject.toml
Labels: enhancement, good first issue, prio:medium, dependencies

#314 RodPlaneContact and RodPlaneContactWithAnisotropicFriction Classes
  elastica/__init__.py
  elastica/contact_forces.py
  elastica/contact_utils.py
  elastica/modules/base_system.py
  elastica/modules/memory_block.py
Labels: enhancement, prio:medium
