Repository GazzolaLab/PyElastica, pull requests merged in 2023-05, with the labels that each got.

#243 (#194) remove internal damping option for Cosserat rod
  elastica/memory_block/memory_block_rod.py
  elastica/rod/cosserat_rod.py
  elastica/rod/factory_function.py
  examples/AxialStretchingCase/axial_stretching.py
  examples/Binder/1_Timoshenko_Beam.ipynb
  examples/Binder/2_Slithering_Snake.ipynb
  examples/BoundaryConditionsCases/general_constraint_allow_yaw.py
  examples/ButterflyCase/butterfly.py
  examples/ContinuumFlagellaCase/continuum_flagella.py
  examples/ContinuumSnakeCase/continuum_snake.py
  examples/DynamicCantileverCase/dynamic_cantilever.py
  examples/ExperimentalCases/GenericSystemConnectionCases/generic_system_type_fixed_joint.py
  examples/ExperimentalCases/GenericSystemConnectionCases/generic_system_type_spherical_joint.py
  examples/ExperimentalCases/ParallelConnectionExample/parallel_connection_example.py
  examples/FlexibleSwingingPendulumCase/flexible_swinging_pendulum.py
  examples/FrictionValidationCases/axial_friction.py
  examples/FrictionValidationCases/rolling_friction_initial_velocity.py
  examples/FrictionValidationCases/rolling_friction_on_inclined_plane.py
  examples/FrictionValidationCases/rolling_friction_torque.py
  examples/HelicalBucklingCase/convergence_helicalbuckling.py
  examples/HelicalBucklingCase/helicalbuckling.py
  examples/JointCases/fixed_joint.py
  examples/JointCases/fixed_joint_torsion.py
  examples/JointCases/hinge_joint.py
  examples/JointCases/spherical_joint.py
  examples/MuscularFlagella/muscular_flagella.py
  examples/MuscularSnake/muscular_snake.py
  examples/RestartExample/restart_example.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_friction.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_validation.py
  examples/RigidBodyCases/RodRigidBodyContact/rod_cylinder_contact_with_y_normal.py
  examples/RingRodCase/ring_rod.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  examples/RodContactCase/RodSelfContact/PlectonemesCase/plectoneme_case.py
  examples/RodContactCase/RodSelfContact/SolenoidsCase/solenoid_case.py
  examples/TimoshenkoBeamCase/convergence_timoshenko.py
  examples/TimoshenkoBeamCase/timoshenko.py
  examples/Visualization/ContinuumSnakeVisualization/continuum_snake.py
  poetry.lock
  pyproject.toml
  tests/test_experimental/test_generic_system_type_joint.py
  tests/test_joint.py
  tests/test_math/test_governing_equations.py
  tests/test_math/test_memory_block_with_symplectic_timestepper.py
  tests/test_memory_block_validity.py
  tests/test_modules/test_base_system.py
  tests/test_modules/test_memory_block.py
  tests/test_restart.py
  tests/test_ring_rod_initialisation.py
  tests/test_rod_initialisation.py
Labels: enhancement, prio:medium

#245 (#244) magnetic cosserat rods functionality
  CONTRIBUTING.md
  README.md
  poetry.lock
  pyproject.toml
Labels: enhancement, prio:medium

#247 changed FixedConstraint example
  README.md
  elastica/boundary_conditions.py
Labels: bug, documentation

#249 239 fix restart functionality
  elastica/__init__.py
  elastica/restart.py
  tests/test_restart.py
Labels: bug, enhancement

#252 remove deprecated v0.3 refs
  docs/guide/workflow.md
  elastica/_elastica_numba.py
  elastica/_elastica_numpy.py
  elastica/interaction.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_inclined_validation.py
  examples/RodContactCase/RodRodContact/rod_rod_contact_parallel_validation.py
  tests/test_interaction.py
Labels: refactor

#253 update readme list of publications and developer names
  README.md
Labels: prio:high

#256 Fix links in README.md
  README.md
Labels: documentation, prio:high

#258 Task 2: Units test for specific functions part-1
  tests/test_contact_specific_functions.py
Labels: enhancement, prio:medium
