Repository GazzolaLab/PyElastica, pull requests merged in 2024-05, with the labels that each got.

#373 Typing: `timestepper` fix pytest and cleanup integration routine
  Makefile
  elastica/modules/base_system.py
  elastica/py.typed
  elastica/systems/analytical.py
  elastica/systems/protocol.py
  elastica/timestepper/__init__.py
  elastica/timestepper/explicit_steppers.py
  elastica/timestepper/protocol.py
  elastica/timestepper/symplectic_steppers.py
  elastica/timestepper/tag.py
  elastica/typing.py
  examples/Binder/1_Timoshenko_Beam.ipynb
  examples/CatenaryCase/catenary.py
  poetry.lock
  pyproject.toml
  tests/test_math/test_timestepper.py
Labels: enhancement

#379 Explicit operation order determined by user definition
  docs/guide/workflow.md
  elastica/modules/base_system.py
  elastica/modules/connections.py
  elastica/modules/contact.py
  elastica/modules/forcing.py
  elastica/modules/operator_group.py
  elastica/typing.py
  tests/test_modules/test_base_system.py
  tests/test_modules/test_connections.py
  tests/test_modules/test_contact.py
  tests/test_modules/test_feature_grouping.py
  tests/test_modules/test_forcing.py
Labels: enhancement, prio:high

#360 Mesh Rigid Body Class
  elastica/__init__.py
  elastica/memory_block/memory_block_rigid_body.py
  elastica/rigidbody/__init__.py
  elastica/rigidbody/cylinder.py
  elastica/rigidbody/mesh_rigid_body.py
  elastica/rigidbody/sphere.py
  tests/test_modules/test_memory_block_rigid_body.py
  tests/test_rigid_body/test_mesh_rigid_body.py
  tests/test_rigid_body_memory_block_validity.py
Labels: enhancement, prio:medium

#383 Feature: check require-modules for each system
  elastica/modules/base_system.py
  elastica/modules/constraints.py
  elastica/rigidbody/rigid_body.py
  elastica/rod/cosserat_rod.py
  elastica/rod/rod_base.py
  elastica/surface/surface_base.py
Labels: enhancement

#341 Typing: Add typehinting for `Rod` modules
  elastica/_calculus.py
  elastica/_contact_functions.py
  elastica/_linalg.py
  elastica/_rotations.py
  elastica/_synchronize_periodic_boundary.py
  elastica/boundary_conditions.py
  elastica/callback_functions.py
  elastica/contact_forces.py
  elastica/contact_utils.py
  elastica/dissipation.py
  elastica/external_forces.py
  elastica/interaction.py
  elastica/joint.py
  elastica/restart.py
  elastica/rod/cosserat_rod.py
  elastica/rod/data_structures.py
  elastica/rod/factory_function.py
  elastica/rod/knot_theory.py
  elastica/rod/rod_base.py
  elastica/transformations.py
  elastica/typing.py
  elastica/utils.py
Labels: enhancement

#389 [GSOC] Feat: minimal cmake files to start integrating pybind11 with blaze
  backend/cmake/.gitignore
  backend/cmake/AddCxxFlag.cmake
  backend/cmake/CheckCompilerVersion.cmake
  backend/cmake/ElasticaAddInterfaceLibraryHeaders.cmake
  backend/cmake/ElasticaSetupFlagsTarget.cmake
  backend/cmake/EnableWarnings.cmake
  backend/cmake/FindBlaze.cmake
  backend/cmake/FindBlazeTensor.cmake
  backend/cmake/FindFilesystem.cmake
  backend/cmake/FindSleef.cmake
  backend/cmake/FindTBB.cmake
  backend/cmake/FindYamlCpp.cmake
  backend/cmake/GetEnvPath.cmake
  backend/cmake/Logging.cmake
  backend/cmake/PrintUsefulCMakeInfo.cmake
  backend/cmake/SetBuildType.cmake
  backend/cmake/SetCxxStandard.cmake
  backend/cmake/SetOutputDirectory.cmake
  backend/cmake/SetupBlaze.cmake
  backend/cmake/SetupBlazeTensor.cmake
  backend/cmake/SetupCxxFlags.cmake
  backend/cmake/SetupElasticaInlining.cmake
  backend/cmake/SetupFilesystem.cmake
  backend/cmake/SetupHDF5.cmake
  backend/cmake/SetupMacOsx.cmake
  backend/cmake/SetupPic.cmake
  backend/cmake/SetupPybind11.cmake
  backend/cmake/SetupSanitizers.cmake
  backend/cmake/SetupSleef.cmake
  backend/cmake/SetupStl.cmake
  backend/cmake/SetupTBB.cmake
  backend/pyproject.toml
  backend/setup.py
  poetry.lock
  pyproject.toml
Labels: GSoC
