Repository GazzolaLab/PyElastica, pull requests merged in 2024-04, with the labels that each got.

#363 update: python version of pyelastica and its CI workflow.
  .github/dependabot.yml
  .github/workflows/main.yml
  README.md
  docs/overview/installation.md
  poetry.lock
  pyproject.toml
Labels: bug, dependencies

#366 add feature: add option to set segment length scaling factor in compute
  elastica/rod/knot_theory.py
Labels: enhancement

#370 Delete .travis.yml
  .travis.yml
Labels: prio:low

#372 Typing: timestepper module
  elastica/__init__.py
  elastica/boundary_conditions.py
  elastica/modules/base_system.py
  elastica/modules/connections.py
  elastica/rod/data_structures.py
  elastica/rod/rod_base.py
  elastica/systems/__init__.py
  elastica/systems/protocol.py
  elastica/timestepper/__init__.py
  elastica/timestepper/explicit_steppers.py
  elastica/timestepper/protocol.py
  elastica/timestepper/symplectic_steppers.py
  elastica/timestepper/tag.py
  elastica/typing.py
  pyproject.toml
  tests/test_contact_classes.py
  tests/test_contact_functions.py
  tests/test_contact_utils.py
  tests/test_joint.py
  tests/test_math/test_timestepper.py
Labels: enhancement, prio:low, github_actions
