Repository GazzolaLab/PyElastica, pull requests merged in 2024-06, with the labels that each got.

#395 Typing: `rigid_body`
  elastica/rigidbody/__init__.py
  elastica/rigidbody/_typing.py
  elastica/rigidbody/cylinder.py
  elastica/rigidbody/data_structures.py
  elastica/rigidbody/rigid_body.py
  elastica/rigidbody/sphere.py
Labels: enhancement, prio:low

#394 Typing: `systems`
  elastica/systems/__init__.py
  elastica/typing.py
Labels: enhancement, prio:low

#382 Typing: `modules`
  elastica/callback_functions.py
  elastica/joint.py
  elastica/memory_block/memory_block_rigid_body.py
  elastica/memory_block/memory_block_rod.py
  elastica/memory_block/memory_block_rod_base.py
  elastica/modules/base_system.py
  elastica/modules/callbacks.py
  elastica/modules/connections.py
  elastica/modules/constraints.py
  elastica/modules/contact.py
  elastica/modules/damping.py
  elastica/modules/forcing.py
  elastica/modules/memory_block.py
  elastica/modules/operator_group.py
  elastica/modules/protocol.py
  elastica/rigidbody/rigid_body.py
  elastica/rod/data_structures.py
  elastica/rod/rod_base.py
  elastica/systems/protocol.py
  elastica/timestepper/__init__.py
  elastica/typing.py
  poetry.lock
  pyproject.toml
  tests/test_joint.py
  tests/test_modules/test_base_system.py
  tests/test_modules/test_callbacks.py
  tests/test_modules/test_constraints.py
  tests/test_modules/test_damping.py
Labels: enhancement, prio:high

#396 Typing: `rods`
  elastica/__init__.py
  elastica/memory_block/memory_block_rod.py
  elastica/memory_block/protocol.py
  elastica/modules/base_system.py
  elastica/modules/memory_block.py
  elastica/rigidbody/rigid_body.py
  elastica/rod/__init__.py
  elastica/rod/cosserat_rod.py
  elastica/rod/data_structures.py
  elastica/rod/knot_theory.py
  elastica/rod/protocol.py
  elastica/rod/rod_base.py
  elastica/surface/plane.py
  elastica/surface/surface_base.py
  elastica/systems/protocol.py
  elastica/typing.py
  elastica/utils.py
  pyproject.toml
  tests/test_rod/test_knot_theory.py
Labels: enhancement

#397 Typing: `contact`
  elastica/__init__.py
  elastica/_synchronize_periodic_boundary.py
  elastica/boundary_conditions.py
  elastica/callback_functions.py
  elastica/collision/AABBCollection.py
  elastica/contact_forces.py
  elastica/contact_utils.py
  elastica/dissipation.py
  elastica/experimental/interaction.py
  elastica/external_forces.py
  elastica/interaction.py
  elastica/joint.py
  elastica/memory_block/memory_block_rigid_body.py
  elastica/memory_block/memory_block_rod.py
  elastica/memory_block/memory_block_rod_base.py
  elastica/memory_block/protocol.py
  elastica/memory_block/utils.py
  elastica/mesh/protocol.py
  elastica/modules/base_system.py
  elastica/modules/connections.py
  elastica/modules/constraints.py
  elastica/modules/contact.py
  elastica/modules/damping.py
  elastica/modules/memory_block.py
  elastica/modules/protocol.py
  elastica/restart.py
  elastica/rigidbody/cylinder.py
  elastica/rigidbody/data_structures.py
  elastica/rigidbody/mesh_rigid_body.py
  elastica/rigidbody/protocol.py
  elastica/rigidbody/rigid_body.py
  elastica/rigidbody/sphere.py
  elastica/rod/data_structures.py
  elastica/rod/knot_theory.py
  elastica/rod/protocol.py
  elastica/rod/rod_base.py
  elastica/surface/plane.py
  elastica/surface/surface_base.py
  elastica/systems/__init__.py
  elastica/systems/analytical.py
  elastica/systems/memory.py
  elastica/systems/protocol.py
  elastica/timestepper/explicit_steppers.py
  elastica/timestepper/symplectic_steppers.py
  elastica/typing.py
  elastica/utils.py
  elastica/wrappers.py
  examples/ContinuumSnakeWithLiftingWaveCase/snake_contact.py
  pyproject.toml
  tests/test_callback_functions.py
  tests/test_contact_classes.py
  tests/test_interaction.py
  tests/test_joint.py
  tests/test_math/test_timestepper.py
  tests/test_modules/test_connections.py
  tests/test_modules/test_contact.py
  tests/test_modules/test_memory_block_rigid_body.py
  tests/test_modules/test_memory_block_utils.py
  tests/test_restart.py
  tests/test_rigid_body/test_rigid_body_data_structures.py
Labels: enhancement
